apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  source:
    repoURL: https://github.com/Shaggydesai/production-kubernetes-platform.git
    targetRevision: feature/ubuntu-template
    path: kubernetes/platform/longhorn
    helm:
      releaseName: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /status
