apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Shaggydesai/production-kubernetes-platform.git
    targetRevision: main
    path: kubernetes/platform/postgresql
    helm:
      releaseName: postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: taskflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /status
