cert-manager:
  crds:
    enabled: true
    keep: true

  replicaCount: 2

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: cert-manager
          app.kubernetes.io/name: cert-manager

  webhook:
    replicaCount: 2

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: webhook
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/name: webhook

  cainjector:
    replicaCount: 2

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: cainjector
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/name: cainjector
