velero:
  kubectl:
    image:
      repository: docker.io/bitnamilegacy/kubectl
      tag: "1.32"
  credentials:
    useSecret: true
    existingSecret: velero-credentials

  configuration:
    defaultVolumesToFsBackup: true
    backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero-backups
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: http://minio.minio.svc:9000
    volumeSnapshotLocation:
      - name: default
        provider: aws
        config:
          region: minio

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0
      volumeMounts:
        - mountPath: /target
          name: plugins

  deployNodeAgent: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

  schedules:
    daily-data:
      disabled: false
      schedule: "0 1 * * *"          # 01:00 UTC = 06:30 IST
      template:
        ttl: "168h"                   # keep 7 days
        storageLocation: default
        defaultVolumesToFsBackup: true
        includedNamespaces:
          - default
          - vault
          - minio
    daily-metadata:
      disabled: false
      schedule: "0 2 * * *"
      template:
        ttl: "336h"                   # keep 14 days
        storageLocation: default
        defaultVolumesToFsBackup: false
        snapshotVolumes: false
        includedNamespaces:
          - "*"  
