---
argocd_namespace: argocd
argocd_release_name: argocd
argocd_chart_repo_name: argo
argocd_chart_repo_url: https://argoproj.github.io/argo-helm
argocd_chart_name: argo/argo-cd
argocd_chart_version: "10.4.0"

argocd_domain: argocd.platform.internal
