apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: taskflow-api
          image: ghcr.io/shaggydesai/taskflow-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgresql.default.svc
            - name: DB_USER
              value: taskflow
            - name: DB_NAME
              value: taskflow
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-api-credentials
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskflow-api-credentials
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
