metallb:
  controller:
    enabled: true

  speaker:
    enabled: true

  crds:
    enabled: true

  frrk8s:
    enabled: false

  prometheus:
    podMonitor:
      enabled: false

    serviceMonitor:
      enabled: false
