argo-cd:
  crds:
    install: true
    keep: true

  createClusterRoles: true

  global:
    domain: argocd.platform.internal

    logging:
      format: json
      level: info

    networkPolicy:
      create: true
      defaultDenyIngress: false

    nodeSelector:
      kubernetes.io/os: linux

    affinity:
      podAntiAffinity: soft

  configs:
    cm:
      create: true
      admin.enabled: true
      exec.enabled: false
      timeout.reconciliation: 120s
      timeout.reconciliation.jitter: 60s

    rbac:
      create: true
      policy.default: ""

  controller:
    replicas: 1

  server:
    replicas: 1
    extraArgs:
      - --insecure

  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1

  dex:
    enabled: false

  notifications:
    enabled: false

  redis:
    enabled: true

  redis-ha:
    enabled: false
