argo-cd:
  crds:
    install: true
    keep: true

  createClusterRoles: true

  global:
    domain: argocd.platform.internal

    logging:
      format: json
      level: info

    networkPolicy:
      create: true
      defaultDenyIngress: false

    nodeSelector:
      kubernetes.io/os: linux

    affinity:
      podAntiAffinity: soft

  configs:
    cm:
      create: true
      admin.enabled: true
      exec.enabled: false
      timeout.reconciliation: 120s
      timeout.reconciliation.jitter: 60s

    rbac:
      create: true
      policy.default: ""

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    replicas: 1

  server:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    replicas: 1
    extraArgs:
      - --insecure

  route:
    enabled: true
    gateway:
      name: platform-gateway
      namespace: envoy-gateway-system
      sectionName: https

  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    replicas: 1

  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    replicas: 1

  dex:
    enabled: false

  notifications:
    enabled: false

  redis:
    enabled: true

  redis-ha:
    enabled: false
