minio:
  mode: standalone
  persistence:
    enabled: true
    storageClass: longhorn-single-replica
    size: 5Gi
  existingSecret: minio-credentials
  buckets:
    - name: velero-backups
      policy: none
      purge: false
  resources:
    requests:
      memory: 256Mi
