{{- if index .Values "argo-cd" "route" "enabled" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: {{ index .Values "argo-cd" "route" "gateway" "name" }}
      namespace: {{ index .Values "argo-cd" "route" "gateway" "namespace" }}
      sectionName: {{ index .Values "argo-cd" "route" "gateway" "sectionName" }}

  hostnames:
    - {{ index .Values "argo-cd" "global" "domain" }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80
{{- end }}
